from datetime import datetime
import json

# Read audit result
with open("reports/audit_report.json", "r", encoding="utf-8") as f:
    report = json.load(f)

report_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

risk = report.get("risk_level", "Low")

if risk == "High":
    risk_color = "red"
elif risk == "Medium":
    risk_color = "orange"
else:
    risk_color = "green"

status_color = "green" if report.get("compliant_status") == "Compliant" else "red"

compliance_percent = max(0, 100 - int(report.get("risk_score", 0)))

html = f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>Privacy-First GRC Audit Report</title>

<style>

body{{
    font-family:Segoe UI,Arial,sans-serif;
    background:#eef3f8;
    margin:0;
    padding:40px;
}}

.container{{
    max-width:1100px;
    margin:auto;
    background:white;
    padding:30px;
    border-radius:15px;
    box-shadow:0 0 20px rgba(0,0,0,.15);
}}

h1{{
    color:#1f4e79;
}}

h2{{
    color:#1f4e79;
    border-bottom:2px solid #1f4e79;
    padding-bottom:8px;
    margin-top:35px;
}}

.audit-info{{
    background:#f4f7fb;
    padding:18px;
    border-radius:10px;
    border-left:5px solid #1f4e79;
    line-height:1.8;
    margin-bottom:25px;
}}

.cards{{
    display:flex;
    gap:20px;
    margin:30px 0;
}}

.card{{
    flex:1;
    padding:25px;
    border-radius:12px;
    color:white;
    text-align:center;
    font-size:22px;
    font-weight:bold;
    box-shadow:0 5px 15px rgba(0,0,0,.15);
    transition:.3s;
}}

.card:hover{{
    transform:translateY(-5px);
}}

.green{{
    background:#2ecc71;
}}

.orange{{
    background:#f39c12;
}}

.red{{
    background:#e74c3c;
}}

.progress-bar{{
    width:100%;
    background:#ddd;
    border-radius:30px;
    overflow:hidden;
    height:32px;
    margin-top:15px;
}}

.progress-fill{{
    height:32px;
    width:{compliance_percent}%;
    background:#2ecc71;
    color:white;
    text-align:center;
    line-height:32px;
    font-weight:bold;
}}

ul{{
    line-height:2;
}}

footer{{
    text-align:center;
    margin-top:40px;
    color:gray;
    font-size:14px;
}}

</style>

</head>

<body>

<div class="container">

<h1>Privacy-First GRC Audit Report</h1>

<div class="audit-info">

<b>Company Name:</b> ABC Technologies<br>

<b>Audit ID:</b> GRC-2026-001<br>

<b>Audit Date:</b> {report_time}<br>

<b>Auditor:</b> Privacy-First AI Agent<br>

<b>Frameworks:</b> ISO 27001 | NIS2 | NIST CSF | GDPR

</div>

<h2>Executive Summary</h2>

<p>

{report.get("summary","This policy was automatically audited using the Privacy-First AI GRC Audit Agent.")}

</p>

<div class="cards">

<div class="card {status_color}">

Compliance

<br><br>

{report.get("compliant_status","Unknown")}

</div>

<div class="card orange">

Risk Score

<br><br>

{report.get("risk_score",0)}

</div>

<div class="card {risk_color}">

Risk Level

<br><br>

{report.get("risk_level","Low")}

</div>

</div>

<h2>Compliance Progress</h2>

<div class="progress-bar">

<div class="progress-fill">

{compliance_percent}% Compliant

</div>

</div>
<h2>Frameworks</h2>

<ul>

{"".join(f"<li>{framework}</li>" for framework in report.get("frameworks", []))}

</ul>

<h2>Compliance Gaps</h2>

<ul>

{"".join(f"<li>{gap}</li>" for gap in report.get("gaps_found", []))}

</ul>

<h2>Remediation Steps</h2>

<ul>

{"".join(f"<li>{step}</li>" for step in report.get("remediation_steps", []))}

</ul>

<h2>Privacy Notice</h2>

<div class="audit-info">

<p>

🔒 This audit was performed entirely on the local device using the
Privacy-First AI Agent.

</p>

<p>

No policy documents or sensitive information were uploaded to any cloud service.

</p>

<p>

🖥️ AI Model: Phi (Ollama Local)

</p>

<p>

📄 Report Version: 1.0

</p>

</div>

<hr>

<footer>

<p><b>Generated By:</b> Privacy-First AI GRC Audit Agent</p>

<p><b>Version:</b> 1.0</p>

<p><b>Report Generated:</b> {report_time}</p>

<p>© 2026 Privacy-First GRC Project</p>

</footer>

</div>

</body>

</html>

"""
with open("reports/audit_report.html", "w", encoding="utf-8") as f:
    f.write(html)

print("==========================================")
print("✅ Professional HTML report generated!")
print("📄 File Location : reports/audit_report.html")
print("==========================================")